"""
THE MANIFESTOR
KALI Phase 33.1: Physical Task Manifestation
Handles creation of project structures, templates, and scaffolding.
"""

import os
import shutil
import logging
import uuid
from typing import Dict, List, Any, Optional

class Manifestor:
    """Bridges the gap between AI architectural plans and physical disk reality."""
    
    def __init__(self, base_path: Optional[str] = None):
        if base_path is None:
            project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
            base_path = os.path.join(project_root, "kali_manifest")
        self.base_path = base_path
        self.base_path = os.path.abspath(base_path)
        self.logger = logging.getLogger(__name__)
        self._ensure_base()
        
    def _ensure_base(self):
        if not os.path.exists(self.base_path):
            os.makedirs(self.base_path, exist_ok=True)
            self.logger.info(f"Manifest base created at {self.base_path}")

    def manifest(self, plan: Dict[str, Any]) -> str:
        """
        Create a physical project structure on disk based on a plan dictionary.
        """
        name = plan.get("title", "unnamed_project")
        # Avoid slice operator to satisfy strict linter
        full_id = uuid.uuid4().hex
        project_id = "".join([full_id[i] for i in range(min(8, len(full_id)))])
        safe_name = "".join([c if c.isalnum() or c in " _-" else "_" for c in name.lower()])
        project_dir = os.path.join(self.base_path, f"{safe_name}_{project_id}")
        
        try:
            os.makedirs(project_dir, exist_ok=True)
            
            # 1. Main Specs / README
            readme_content = f"# {name}\n\nGenerated by KALI Project Mentor.\n\n"
            readme_content += f"## Problem Statement\n{plan.get('problem_statement', '')}\n\n"
            
            materials = plan.get("materials", [])
            if materials:
                readme_content += f"## Bill of Materials\n"
                for m in materials:
                    # Handle both list of strings and list of dicts
                    if isinstance(m, dict):
                        item = m.get('item', 'Unknown')
                        cost = m.get('cost', 'N/A')
                        link = m.get('link', 'No link')
                        readme_content += f"- {item}: {cost} ({link})\n"
                    else:
                        readme_content += f"- {m}\n"
            
            with open(os.path.join(project_dir, "README.md"), "w", encoding="utf-8") as f:
                f.write(readme_content)
                
            # 2. Structure Manifestation
            structure = plan.get("structure", [])
            if isinstance(structure, dict):
                self._create_recursive(project_dir, structure)
            elif isinstance(structure, list):
                for item in structure:
                    path = os.path.join(project_dir, item)
                    if item.endswith("/") or "." not in item:
                        os.makedirs(path, exist_ok=True)
                    else:
                        os.makedirs(os.path.dirname(path), exist_ok=True)
                        with open(path, "w", encoding="utf-8") as f:
                            f.write(f"# Auto-generated by KALI for {name}\n")
            
            self.logger.info(f"Manifest created at: {project_dir}")
            return project_dir
            
        except Exception as e:
            self.logger.error(f"Manifestation failed: {e}")
            return ""

    def _create_recursive(self, current_path: str, structure: Dict[str, Any]):
        for key, value in structure.items():
            path = os.path.join(current_path, key)
            if isinstance(value, dict):
                os.makedirs(path, exist_ok=True)
                self._create_recursive(path, value)
            else:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(str(value))

    def clean_manifest(self, name: str):
        """Removes a manifested project."""
        project_path = os.path.join(self.base_path, name)
        if os.path.exists(project_path):
            shutil.rmtree(project_path)
            return True
        return False

if __name__ == "__main__":
    # Test Manifestation
    logging.basicConfig(level=logging.INFO)
    m = Manifestor()
    test_plan = {
        "title": "Test Project",
        "problem_statement": "Testing KALI manifestation engine.",
        "structure": {
            "src": {
                "main.py": "print('KALI ONLINE')"
            },
            "README.md": "# Overwritten README"
        }
    }
    res = m.manifest(test_plan)
    print(f"Result: {res}")
